(function(){document.addEventListener('DOMContentLoaded',function(){var root=document.querySelector('.veeaardvark');if(!root)return;initHeroCarousel(root);initVeeSliders(root)});function initHeroCarousel(root){var carousel=root.querySelector('.veeaardvark-carousel');if(!carousel)return;var track=carousel.querySelector('.veeaardvark-slides');var slides=carousel.querySelectorAll('.veeaardvark-slide');var prevBtn=carousel.querySelector('[data-car-prev]');var nextBtn=carousel.querySelector('[data-car-next]');var dotsContainer=document.getElementById('veeaardvark-bannerDots');if(!track||!slides.length)return;var index=0;var autoTimer=null;var AUTO_MS=6000;function goToSlide(newIndex){var max=slides.length;if(!max)return;if(newIndex<0)newIndex=max-1;if(newIndex>=max)newIndex=0;index=newIndex;var offsetPercent=-index*100;track.style.transform='translateX('+offsetPercent+'%)';updateDots()}
function updateDots(){if(!dotsContainer)return;var dots=dotsContainer.querySelectorAll('.veeaardvark-dot');if(!dots.length)return;for(var i=0;i<dots.length;i++){var isCurrent=i===index;dots[i].setAttribute('aria-current',isCurrent?'true':'false');if(isCurrent){dots[i].classList.add('is-active')}else{dots[i].classList.remove('is-active')}}}
function startAuto(){stopAuto();autoTimer=window.setInterval(function(){goToSlide(index+1)},AUTO_MS)}
function stopAuto(){if(autoTimer){window.clearInterval(autoTimer);autoTimer=null}}
if(prevBtn){prevBtn.addEventListener('click',function(){goToSlide(index-1)})}
if(nextBtn){nextBtn.addEventListener('click',function(){goToSlide(index+1)})}
if(dotsContainer){var dots=dotsContainer.querySelectorAll('.veeaardvark-dot');for(var d=0;d<dots.length;d++){(function(dotIndex){dots[dotIndex].addEventListener('click',function(){goToSlide(dotIndex)})})(d)}}
carousel.addEventListener('mouseenter',stopAuto);carousel.addEventListener('mouseleave',startAuto);goToSlide(0);startAuto()}
function initVeeSliders(root){var sliders=root.querySelectorAll('.vee-slider');if(!sliders.length)return;for(var i=0;i<sliders.length;i++){initSingleSlider(sliders[i])}}
function initSingleSlider(slider){var viewport=slider.querySelector('.vee-slider-viewport');var track=slider.querySelector('.vee-slider-track');var cards=slider.querySelectorAll('.vee-slider-card');var prevBtn=slider.querySelector('[data-slider-prev]');var nextBtn=slider.querySelector('[data-slider-next]');if(!viewport||!track||!cards.length||!prevBtn||!nextBtn)return;var currentIndex=0;function getMaxIndex(){return cards.length-1}
function scrollToIndex(idx,smooth){var maxIndex=getMaxIndex();if(idx<0)idx=0;if(idx>maxIndex)idx=maxIndex;currentIndex=idx;var targetCard=cards[currentIndex];if(!targetCard)return;var targetLeft=targetCard.offsetLeft;try{viewport.scrollTo({left:targetLeft,behavior:smooth?'smooth':'auto'})}catch(e){viewport.scrollLeft=targetLeft}
updateButtons()}
function updateButtons(){var maxIndex=getMaxIndex();prevBtn.disabled=currentIndex<=0;nextBtn.disabled=currentIndex>=maxIndex}
function syncIndexToScroll(){var scrollLeft=viewport.scrollLeft;var closestIndex=0;var closestDist=Infinity;for(var i=0;i<cards.length;i++){var cardLeft=cards[i].offsetLeft;var dist=Math.abs(cardLeft-scrollLeft);if(dist<closestDist){closestDist=dist;closestIndex=i}}
if(closestIndex!==currentIndex){currentIndex=closestIndex;updateButtons()}}
prevBtn.addEventListener('click',function(){scrollToIndex(currentIndex-1,!0)});nextBtn.addEventListener('click',function(){scrollToIndex(currentIndex+1,!0)});viewport.addEventListener('scroll',function(){syncIndexToScroll()});enableDragScroll(viewport);viewport.setAttribute('tabindex','0');viewport.addEventListener('keydown',function(e){if(e.key==='ArrowRight'){e.preventDefault();scrollToIndex(currentIndex+1,!0)}else if(e.key==='ArrowLeft'){e.preventDefault();scrollToIndex(currentIndex-1,!0)}});window.addEventListener('resize',function(){scrollToIndex(currentIndex,!1)});scrollToIndex(0,!1)}
function enableDragScroll(viewport){var isDown=!1;var startX=0;var startScrollLeft=0;viewport.addEventListener('mousedown',function(e){isDown=!0;viewport.classList.add('vee-slider--dragging');startX=e.pageX;startScrollLeft=viewport.scrollLeft});document.addEventListener('mousemove',function(e){if(!isDown)return;var dx=e.pageX-startX;viewport.scrollLeft=startScrollLeft-dx});document.addEventListener('mouseup',function(){if(!isDown)return;isDown=!1;viewport.classList.remove('vee-slider--dragging')})}})()
