(function(){document.addEventListener('DOMContentLoaded',function(){var popupWrapper=document.querySelector('.veepopup');if(!popupWrapper)return;var popup=popupWrapper.querySelector('#veeOfferPopup');var card=popupWrapper.querySelector('#veeOfferCard');var closeBtn=popupWrapper.querySelector('[data-offer-close]');var handle=popupWrapper.querySelector('.vee-offer-handle');var parallaxLayer=popupWrapper.querySelector('#veeOfferParallax');var activateBtn=popupWrapper.querySelector('#veeOfferActivate');if(!popup||!card)return;function isMobile(){return window.innerWidth<=767}
function getMobileDismissed(){try{return(!!window.localStorage&&localStorage.getItem('veeOfferDismissedMobile')==='1')}catch(e){return!1}}
function setMobileDismissed(){try{if(window.localStorage){localStorage.setItem('veeOfferDismissedMobile','1')}}catch(e){}}
function openDesktop(){popup.classList.add('is-open');popup.classList.remove('vee-offer-popup--collapsed');popupWrapper.style.display='';popupWrapper.setAttribute('aria-hidden','false')}
function collapseDesktop(){popup.classList.remove('is-open');popup.classList.add('vee-offer-popup--collapsed');popupWrapper.style.display='';popupWrapper.setAttribute('aria-hidden','true')}
function showMobile(){popupWrapper.style.display='';popup.classList.add('is-open');popup.classList.remove('vee-offer-popup--collapsed');popupWrapper.setAttribute('aria-hidden','false')}
function hideMobile(){popupWrapper.style.display='none';popupWrapper.setAttribute('aria-hidden','true')}
function applyLayoutState(){if(isMobile()){if(getMobileDismissed()){hideMobile()}else{showMobile()}}else{popupWrapper.style.display='';collapseDesktop()}}
applyLayoutState();function handleCloseClick(event){if(event)event.stopPropagation();if(isMobile()){setMobileDismissed();hideMobile()}else{collapseDesktop()}}
if(closeBtn){closeBtn.addEventListener('click',handleCloseClick)}
popupWrapper.addEventListener('click',function(event){if(!isMobile())return;if(event.target===popupWrapper){handleCloseClick(event)}});if(activateBtn){activateBtn.addEventListener('click',function(event){event.stopPropagation();window.location.href='/sign-up'})}
if(handle){handle.addEventListener('click',function(event){event.stopPropagation();if(isMobile())return;var isOpen=popup.classList.contains('is-open')&&!popup.classList.contains('vee-offer-popup--collapsed');if(isOpen){collapseDesktop()}else{openDesktop()}})}
popup.addEventListener('mouseenter',function(){if(isMobile())return;openDesktop()});popup.addEventListener('mouseleave',function(){if(isMobile())return;collapseDesktop()});function handleTilt(event){if(isMobile())return;var rect=card.getBoundingClientRect();var x=event.clientX-rect.left;var y=event.clientY-rect.top;var midX=rect.width/2;var midY=rect.height/2;var rotateX=((midY-y)/midY)*6;var rotateY=((x-midX)/midX)*6;card.style.setProperty('--rotateX',rotateX.toFixed(2)+'deg');card.style.setProperty('--rotateY',rotateY.toFixed(2)+'deg');card.style.setProperty('--scale','1.02');if(parallaxLayer){var tX=((x-midX)/midX)*12;var tY=((y-midY)/midY)*12;parallaxLayer.style.transform='translate3d('+tX.toFixed(1)+'px,'+tY.toFixed(1)+'px,0)'}}
function resetTilt(){card.style.setProperty('--rotateX','0deg');card.style.setProperty('--rotateY','0deg');card.style.setProperty('--scale','1');if(parallaxLayer){parallaxLayer.style.transform='translate3d(0,0,0)'}}
card.addEventListener('mousemove',handleTilt);card.addEventListener('mouseleave',resetTilt);window.addEventListener('resize',function(){applyLayoutState()})})})()
