(function(){const STORAGE_KEY="veeWelcomePackSeen_v1";const root=document.querySelector(".veepopup");if(!root)return;const popup=root.querySelector("#veeOfferPopup");const card=root.querySelector("#veeOfferCard");const chip=root.querySelector("#veeOfferChip");const parallax=root.querySelector("#veeOfferParallax");const trigger=root.querySelector("#veeOfferTrigger");const closeBtn=root.querySelector("[data-offer-close]");const activateBtn=root.querySelector("#veeOfferActivate");const miniCards=root.querySelectorAll(".vee-offer-card-mini");if(!popup||!card||!trigger)return;let hasSeen=!1;try{hasSeen=window.localStorage.getItem(STORAGE_KEY)==="1"}catch(e){hasSeen=!1}
function markSeenForever(){try{window.localStorage.setItem(STORAGE_KEY,"1")}catch(e){}
popup.classList.remove("is-visible");if(trigger){trigger.style.display="none";trigger.setAttribute("aria-expanded","false")}}
function openOnce(){if(hasSeen){if(trigger)trigger.style.display="none";return}
popup.classList.add("is-visible");if(trigger)trigger.setAttribute("aria-expanded","true");}
openOnce();function onTriggerClick(){if(!popup.classList.contains("is-visible"))return;markSeenForever()}
trigger.addEventListener("click",onTriggerClick);if(closeBtn){closeBtn.addEventListener("click",function(e){e.stopPropagation();markSeenForever()})}
popup.addEventListener("click",(e)=>{if(e.target===popup){markSeenForever()}});document.addEventListener("keydown",(e)=>{if(e.key==="Escape"&&popup.classList.contains("is-visible")){markSeenForever()}});if(activateBtn){activateBtn.addEventListener("click",()=>{window.location.href="/sign-up";markSeenForever()})}
miniCards.forEach((el)=>{el.addEventListener("click",()=>{el.classList.add("vee-offer-card-mini--ping");setTimeout(()=>el.classList.remove("vee-offer-card-mini--ping"),180)})});const isFinePointer=window.matchMedia("(pointer: fine)").matches;if(!isFinePointer)return;let rect=null;const maxRotate=10;const hoverScale=1.04;function updateRect(){rect=card.getBoundingClientRect()}
window.addEventListener("resize",()=>{if(popup.classList.contains("is-visible"))updateRect();});function isOnClose(target){return target&&target.closest&&target.closest(".vee-offer-popup__close")}
card.addEventListener("pointermove",(event)=>{if(!popup.classList.contains("is-visible"))return;if(isOnClose(event.target))return;if(!rect)updateRect();const x=event.clientX-rect.left;const y=event.clientY-rect.top;const centerX=rect.width/2;const centerY=rect.height/2;const percentX=(x-centerX)/centerX;const percentY=(y-centerY)/centerY;const rotateY=(percentX*maxRotate).toFixed(2);const rotateX=(-percentY*maxRotate).toFixed(2);card.style.setProperty("--rotateX",rotateX+"deg");card.style.setProperty("--rotateY",rotateY+"deg");card.style.setProperty("--scale",hoverScale);card.dataset.tiltActive="1";if(chip){const chipX=(percentX*10).toFixed(1);const chipY=(percentY*8).toFixed(1);chip.style.transform=`translate3d(${chipX}px, ${chipY}px, 40px)`}
if(parallax){const px=(percentX*18).toFixed(1);const py=(percentY*14).toFixed(1);parallax.style.transform=`translate3d(${px}px, ${py}px, 0)`}});card.addEventListener("pointerleave",()=>{card.style.setProperty("--rotateX","0deg");card.style.setProperty("--rotateY","0deg");card.style.setProperty("--scale","1");card.dataset.tiltActive="0";if(chip)chip.style.transform="translate3d(0,0,40px)";if(parallax)parallax.style.transform="translate3d(0,0,0)"});card.addEventListener("pointerdown",(event)=>{if(isOnClose(event.target))return;card.style.setProperty("--scale","1.02")});card.addEventListener("pointerup",(event)=>{if(isOnClose(event.target))return;card.style.setProperty("--scale",hoverScale)})})()
